version: "3.8"

services:
  db:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    volumes:
      - ./backend:/backend
    depends_on:
      - db
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    # ports:
    #   - 3000:3000
    expose:
      - 3000
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/node_modules:/frontend/node_modules
    depends_on:
      - backend
  reverse_proxy:
    build: ./nginx
    ports:
      - 81:80
    depends_on:
      - backend
      - frontend